n_agents: 1

dataset:
  name: cifar10
  train_size: 512
  val_size: 256
  test_size: 1.0
  num_cls_per_task: 10
  num_task_per_life: 1

task_model:
  device: cuda
  name: cifar10

training:
  batch_size: 128
  n_epochs: 300
  patience: 10
  delta: 0.0
  val_every_n_epoch: 10

experience_replay:
  train_size: 256

data_valuation:
  strategy: best_mean
  threshold: 0.0
  train_size: 10240


router:
  n_heads: 1
  strategy: neural
  batch_size: 64
  num_batches: 4
  train_size: 128
  val_size: 64
  explore:
    num_slates: 64
    epsilon: 1.0
    min_epsilon: 0.01
    decay_rate: 0.8
  training:
    batch_size: 64
    n_epochs: 200
    patience: 10
    delta: 0.0
    val_every_n_epoch: 10
  estimator_task_model:
    name: cifar10
    device: cuda

defaults:
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none